module.exports = {
  ECI_PUBLIC_KEY: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtAIUyGaNWpthLLU3Iy3a
jrKt5slwJjuGbks+qEuSPHSA+uknzHcdujr4svP2INJoTNxNzfMUk5+IItKeSPSZ
VGkwEhJE1XJ4ofraOiMY+zvunH1UIOkYFPh5Ib2U4iGC1Rsxo3Awah5VaIcN8Yjj
czYVqaQ6krQastyazskA52NV7ciUD+pVG3p6ufo6NR67w8pzi9GcE443JhYq36+f
MZKiVuueTuJ9cH5X9IjBYz50YPpsMTk9KmrhqOHWiIVGOkMYnWZHsdS/qnEovORE
MIBwtMQPeDDi5sP5UXmF9oZ5Oc6t8yWKuWjtYB9wpPipXYmtcTPxJypD2DHdRoby
RwIDAQAB
-----END PUBLIC KEY-----`
};
