/**
 * VoterPath Authoritative Public Keys (TEST ENVIRONMENT)
 */
const ECI_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlkqFSlA8MnhpRJmwtfGC
zJ89myqOl6LJRk7nqilYamFqtiHHylmj4kohXoJ1ZXCinAWvmPOYSC7a5On3NXHf
TTMur11+rhczStrjlng7E56jdJ+Pom3xA279whgqjGVBKDmpWpj8Qz8N6BE1EGbV
UpvqwBvfch+MfP5l1hsQ8D9NQKdf+R9g2tjEM0IlOVoEz2T5spmnxQ2XoJfrKEmQ
gs/XGdPOPXeH/6X1WoJBgWVI/nUO8CPt4ISu/ABEy35TVzdmaOtuOd1mlFw+OZdV
E1TXvXSbtqYev5We9BTiqoKWBaiFVVSXd8uoLzaQGr5zUilZwEMpC0IqwC97Djzh
ewIDAQAB
-----END PUBLIC KEY-----
`;

module.exports = { ECI_PUBLIC_KEY };
